### ISSUE TITLE
ALUctrl width mismatch

### ISSUE THREAD

**Issue by torpeyl** [b4shful/Lab4#6]
The control unit aluctrl output only has 1 bit since we're only using 2 instructions for this first section but the alu is expecting 3 bits.

**Comment by b4shful** [comment]
@torpeyl block diagram on lab4 slides shows a 3 bit ALUcontrol

I would suggest therefore that the control block would implement the table in the slides which supports 5 arithmetic operations add, subtract, add, or and SLT. @aaashah should implement this. There is MUCH more detail about implementation in Peter Cheung's lecture 7 "notes" (rather than slides) so I would use these.

This 3 bit ALUctrl is more than required to run the program, but less than required to implement full RV32I. I suspect eventually ALUctrl will be 5 bits. So let's maybe use 3 bits for now.

If you ctrl-shift-P and type "compile" you should see a SystemVerilog task in vscode that does a test compile of the current file w verilator and shows any errors. (It doesn't generate any outputs so don't worry it doesn't try to properly compile I think it's just for error checking purposes). This might help to use as a linter.

Thanks for checking for bugs :)
